# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentsync" do
  version "0.10.0"

  on_macos do
    on_intel do
      sha256 "4dc534b7c8bd032f14b96b0b1f06b3e632f52e97c10dcbee55a15883a8e84cc3"
      url "https://github.com/x0c/agentsync/releases/download/v#{version}/agentsync_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "02430ef50b5b55f7ea7de3053b0af0d38483d5d2dfa2e28c60e75a3b855c4f81"
      url "https://github.com/x0c/agentsync/releases/download/v#{version}/agentsync_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1f4233792f73907779c956c6974c540585ab4c00ae07fa61c301575a61bea479"
      url "https://github.com/x0c/agentsync/releases/download/v#{version}/agentsync_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "81139aff5022ca3210116df55df9be0c660ac261096107c058d8d759292029be"
      url "https://github.com/x0c/agentsync/releases/download/v#{version}/agentsync_linux_arm64.tar.gz"
    end
  end

  name "agentsync"
  desc "Keep AI coding-agent instructions and reusable skills in one canonical place"
  homepage "https://github.com/x0c/agentsync"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentsync"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agentsync"]
    end
  end

  # No zap stanza required

end
