# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentsync" do
  version "0.16.0"

  on_macos do
    on_arm do
      sha256 "6f5883b80d1226eafa8a61ed2e2505c60637114b3eeaca39bdc17a86e03cbb17"
      url "https://github.com/x0c/agentsync/releases/download/v#{version}/agentsync_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "263af3289e0531536063df524d9d9886e499fbfb4e4e28b0649084bd293d93ba"
      url "https://github.com/x0c/agentsync/releases/download/v#{version}/agentsync_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d21743219ce9d057538dd29b0655891df1a86c66a4b9543721a1c87e7ebed7f9"
      url "https://github.com/x0c/agentsync/releases/download/v#{version}/agentsync_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "fc65fc19b459ed965304688a94ef0027f249c92f714ff8a4439e298f9cb8e6b0"
      url "https://github.com/x0c/agentsync/releases/download/v#{version}/agentsync_linux_amd64.tar.gz"
    end
  end

  name "agentsync"
  desc "Keep AI coding-agent instructions and reusable skills in one canonical place"
  homepage "https://github.com/x0c/agentsync"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentsync"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agentsync"]
    end
  end

  # No zap stanza required
end
