# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentsync" do
  version "0.16.1"

  on_macos do
    on_arm do
      sha256 "d42ff0ed8034ff3123c391da90d41a1755a85894255a0f04bae250911095739d"
      url "https://github.com/x0c/agentsync/releases/download/v#{version}/agentsync_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ccfbe35c1ed4fc5f7212f561dcaf80a0b39bee9da13a97b25ce1a71398c12182"
      url "https://github.com/x0c/agentsync/releases/download/v#{version}/agentsync_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d630330e73662b3e2b7717723f05ca3d9464fac151aa0a3ed03402b5c833710f"
      url "https://github.com/x0c/agentsync/releases/download/v#{version}/agentsync_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d6adc307825a8b3ab28bc1da9d9c7f9cd9278bc57292a0916195711731d3b28a"
      url "https://github.com/x0c/agentsync/releases/download/v#{version}/agentsync_linux_amd64.tar.gz"
    end
  end

  name "agentsync"
  desc "Keep AI coding-agent instructions and reusable skills in one canonical place"
  homepage "https://github.com/x0c/agentsync"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentsync"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agentsync"]
    end
  end

  # No zap stanza required
end
