# This file was generated by GoReleaser. DO NOT EDIT.
cask "bluebird" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "ff8a2b95cbb174c9d48b72eff6eb94d6bdcc7a55fc9604542d51f375ee006ce6"
      url "https://github.com/x0c/bluebird-cli/releases/download/v#{version}/bluebird_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ae4b2466911637c833f50eaced7590850c7860449c185048132a1de3be396a8b"
      url "https://github.com/x0c/bluebird-cli/releases/download/v#{version}/bluebird_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "72960249b154d7516f0444d741394a9ce2515426c992ad9b3d4062d4c9d953fe"
      url "https://github.com/x0c/bluebird-cli/releases/download/v#{version}/bluebird_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b8baa83f9c776be874f2779d4efa13c1059394ff4c7b31081afd10c82ce342fa"
      url "https://github.com/x0c/bluebird-cli/releases/download/v#{version}/bluebird_linux_arm64.tar.gz"
    end
  end

  name "bluebird"
  desc "Agent-friendly CLI for the Bluebird weather-discovery service"
  homepage "https://github.com/x0c/bluebird-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bluebird"

  # No zap stanza required

end
